# Generated by Django 6.0.6 on 2026-06-28 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rubro', models.CharField(blank=True, max_length=150, null=True)),
                ('tamano', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('ingresos_anuales', models.CharField(blank=True, max_length=100, null=True)),
                ('programa_sostenibilidad', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema_detectado', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('operativa', 'Operativa'), ('anormal', 'Anormal')], max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('impacto_economico', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='dashboard.empresa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.etapaproductiva')),
            ],
        ),
    ]
